use helpsystem;
CREATE TABLE `helpsystem`.`TB_USER` (
  `ID_USER` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `STR_USER` VARCHAR(45) NOT NULL,
  `STR_NOME_PESSOA` VARCHAR(100) NOT NULL,
  `STR_EMAIL` VARCHAR(100) NOT NULL,
  `STR_SENHA` VARCHAR(45) NOT NULL,
  `DT_ULTIMA_ALTERACAO` DATE NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE INDEX `STR_USER_UNIQUE` (`STR_USER` ASC) VISIBLE)
COMMENT = 'Tabela de usuario';

DROP TABLE `helpsystem`.`TB_PERGUNTAS`;
CREATE TABLE `helpsystem`.`TB_PERGUNTAS` (
  `ID_PERGUNTA` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `ID_USER` MEDIUMINT NOT NULL,
  `STR_TITULO` VARCHAR(200) NULL,
  `STR_PERGUNTA` TEXT NULL,
  `FLAG_RESOLVIDO` boolean NULL,
  `DT_PERGUNTA` DATE NULL,
  PRIMARY KEY (`ID_PERGUNTA`));

DROP TABLE  `helpsystem`.`TB_RESPOSTAS`;
CREATE TABLE  `helpsystem`.`TB_RESPOSTAS` (
  `ID_RESPOSTA` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `ID_PERGUNTA` MEDIUMINT NOT NULL,
  `ID_USER` MEDIUMINT NOT NULL,
  `FLAG_MELHOR_RESPOSTA` boolean NULL,
  `STR_RESPOSTA` TEXT NULL,
  `DT_RESPOSTA` DATE NULL,
  PRIMARY KEY (`ID_RESPOSTA`));
  
  select * from `helpsystem`.`TB_USER` ;
  